### 提交任务
POST http://localhost:18080/comfy_ui/prompt
Authorization: xxx-xyz
Content-Type: application/json

{
  "3": {
    "inputs": {
      "seed": 675382167425780,
      "steps": 20,
      "cfg": 6,
      "sampler_name": "euler_ancestral",
      "scheduler": "normal",
      "denoise": 1,
      "model": [
        "12",
        0
      ],
      "positive": [
        "6",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "latent_image": [
        "12",
        1
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "4": {
    "inputs": {
      "ckpt_name": "epicrealism_pureEvolutionV5.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "6": {
    "inputs": {
      "text": "masterpiece, best quality,\nsensitive, 1girl, looking at viewer, blush, jewelry, tears, 1girl, long hair, looking at viewer, blush, open mouth, bangs, brown hair, hair between eyes, bare shoulders, jewelry, upper body, earrings, solo focus, tears, blurry, bracelet, blurry background, crying, crying with eyes open",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "7": {
    "inputs": {
      "text": "nsfw, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name\n",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "8": {
    "inputs": {
      "samples": [
        "26",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "9": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "8",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  },
  "10": {
    "inputs": {
      "image": "0-org (1).png",
      "upload": "image"
    },
    "class_type": "LoadImage",
    "_meta": {
      "title": "Load Image"
    }
  },
  "11": {
    "inputs": {
      "pixels": [
        "24",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEEncode",
    "_meta": {
      "title": "VAE Encode"
    }
  },
  "12": {
    "inputs": {
      "batch_size": 1,
      "model": [
        "4",
        0
      ],
      "reference": [
        "11",
        0
      ]
    },
    "class_type": "ReferenceOnlySimple",
    "_meta": {
      "title": "ReferenceOnlySimple"
    }
  },
  "24": {
    "inputs": {
      "side_length": 1024,
      "side": "Longest",
      "upscale_method": "nearest-exact",
      "crop": "disabled",
      "image": [
        "10",
        0
      ]
    },
    "class_type": "Image scale to side",
    "_meta": {
      "title": "Image scale to side"
    }
  },
  "26": {
    "inputs": {
      "batch_index": 1,
      "length": 1,
      "samples": [
        "3",
        0
      ]
    },
    "class_type": "LatentFromBatch",
    "_meta": {
      "title": "Latent From Batch"
    }
  }
}

### 上传图片
POST http://localhost:18080/comfy_ui/upload/image
Authorization: xxx-hxy
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="subfolder"
Content-Type: text/plain

abc
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ai.png"

< ./ai.png
--WebAppBoundary--


### 查询状态
GET http://localhost:18080/comfy_ui/history/8dc2598b-732c-4628-bc87-ca081677aaec
Authorization: xxx-hxy


### 下载图片
GET http://localhost:18080/comfy_ui/view?filename=ai.png&subfolder=abc&type=input
Authorization: xxx-hxy


### 健康检查
#GET https://u293571-addd-e64a6733.bjb1.seetacloud.com:8443/prompt
GET http://region-41.seetacloud.com:12476/prompt
Content-Type: application/json