### Chat
POST http://45.78.59.198:18080/openai/v1/chat/completions
#Authorization: xxx-xyz
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": false
}